### ISSUE TITLE
Worksheet#setFreezePanes missing

### ISSUE THREAD

**Issue by henrikekblad** [estie-inc/wasm-xlsxwriter#19]
Haha.. Sorry for this stream of issues... And I really appriciate your responsiveness!
When finished porting our export I will post some comparison between the rust wasm-xmlwriter compared to the go excelize-wasm we're using today on large file generation. My suspicion is that rust-wasm will be faster with a much smaller footprint.

**Comment by tamaroning** [comment]
Thanks for reporting!
This project is in a very early stage so it is great to see people like you using this library and requesting new features.
I am also glad to hear this good news. This library just wraps everything in rust-xlsxwriter. I believe good performance is due to the original Rust implementation and rustc+wasm-bindgen :)
