### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by jmcnamara** [estie-inc/wasm-xlsxwriter#5]
As the author of `rust_xlsxwriter` I just wanted to say that this looks really useful and very complete. Well done.

**Comment by kenkoooo** [comment]
Thank you for your kind words! I'm glad to hear you find it useful. Your work on `rust_xlsxwriter` made it a pleasure to build on, and I hope this wrapper can help others make the most of your fantastic library.

**Comment by jmcnamara** [comment]
Could I ask a little bit about the technical aspects. Just for my information and learning. :-)

I see that you re-wrapped the `rust_xlsxwriter` structs as inner objects in similar structs as the `wasm-xlsxwriter` level. Was that to make the `bindgen` step easier or for some other reason.

Also, why did you create this wasm version rather than use SheetJS or similar. (I'm glad that you did by the way. I was just interested in your motivation.)

**Comment by tamaroning** [comment]
@jmcnamara 
Hello, thank you for your questions.

> I see that you re-wrapped the rust_xlsxwriter structs as inner objects in similar structs as the wasm-xlsxwriter level. Was that to make the bindgen step easier or for some other reason.

At the first attempt, we tried to fork rust-xlsxwriter and attach #[wasm_bidngen] to every struct and function but it was impossible because wasm-bindgen does not support functions (and methods) that return references. So we re-wrapped all structs and functions so that all function return `T` instead of `&T` and `&mut T`.

The code below is an example of this: (note that add_worksheet originally returns `&mut Worksheet`)

https://github.com/estie-inc/wasm-xlsxwriter/blob/9b978011227956a181419f79fa4d86c03c4ec9c7/rust/src/wrapper/workbook.rs#L69-L78
https://github.com/estie-inc/wasm-xlsxwriter/blob/9b978011227956a181419f79fa4d86c03c4ec9c7/rust/src/wrapper/worksheet.rs#L23-L26

> Also, why did you create this wasm version rather than use a pure Javascript library like SheetJS.

First, SheetJS supports embedding images into cells only in the Pro edition. AFAIK, other famous libraries such as exceljs do not support it either.

**Comment by jmcnamara** [comment]
Thank you for the explanation.
